### ISSUE TITLE
지도 위에 스팟 스티커 배치하기

### ISSUE THREAD

**Issue by dev-owen** [Nexters/DaeDongYeoMap-Frontend#29]
# 작업목표

- 현재 위치 기반 붙어있는 스팟 스티커 보여주기
- 10개, 100개, 1000개 이상의 스티커 겹치게 보여주기
- 검색 후 클릭한 스팟으로 지도 이동시키기
- 스팟 클릭 시 상세 정보 보여주기
- 스팟찍기 레이어를 통해 새로운 스팟 등록하기

**Comment by devjaewon** [comment]
#58 에서 다룰 예정으로 이슈 닫음
